// Generates web-ready AVIF masters + blur placeholders from the raw library.
//
//   Source:  public/_originals/<original filename>   (git-ignored, huge)
//   Output:  public/works/<slug>.avif                (committed, optimized)
//            src/data/works-images.generated.ts       (dimensions + blur data)
//
// next/image then derives responsive sizes from each AVIF master on demand.
// Run with:  npm run images

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import sharp from "sharp";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const ORIGINALS = path.join(root, "public/_originals");
const OUT = path.join(root, "public/works");
const DATA = path.join(root, "src/data/works-images.generated.ts");

// source file  ->  slug used everywhere in the app
const MAP = [
  { file: "red knott.png", slug: "red-knott" },
  { file: "heritage board.avif", slug: "heritage-board" },
  { file: "festive favourites.png", slug: "festive-favourites" },
  { file: "birthday sale.png", slug: "birthday-sale" },
  { file: "hoodie mockup.png", slug: "hoodie-mockup" },
  { file: "snakes and ladders.jpg", slug: "snakes-and-ladders" },
  { file: "PEACE.png", slug: "peace" },
  { file: "infographic.avif", slug: "infographic" },
  { file: "10.png", slug: "campaign-ten" },
  { file: "6.png", slug: "editorial-spread" },
  { file: "6 - Copy.png", slug: "editorial-spread-two" },
  { file: "1 - Copy.png", slug: "identity-study" },
  { file: "3 - Copy (2).png", slug: "identity-study-two" },
];

const MAX_EDGE = 2000; // long-edge cap for the master
const QUALITY = 62;

await mkdir(OUT, { recursive: true });

const records = [];

for (const { file, slug } of MAP) {
  const input = await readFile(path.join(ORIGINALS, file));
  const img = sharp(input, { failOn: "none" });
  const meta = await img.metadata();

  const longEdge = Math.max(meta.width ?? 0, meta.height ?? 0);
  const scale = longEdge > MAX_EDGE ? MAX_EDGE / longEdge : 1;
  const width = Math.round((meta.width ?? 0) * scale);
  const height = Math.round((meta.height ?? 0) * scale);

  // optimized master
  await sharp(input, { failOn: "none" })
    .resize(width, height, { fit: "inside" })
    .avif({ quality: QUALITY, effort: 4 })
    .toFile(path.join(OUT, `${slug}.avif`));

  // tiny blur placeholder (base64 webp)
  const blur = await sharp(input, { failOn: "none" })
    .resize(20, 20, { fit: "inside" })
    .webp({ quality: 40 })
    .toBuffer();
  const blurDataURL = `data:image/webp;base64,${blur.toString("base64")}`;

  records.push({ slug, src: `/works/${slug}.avif`, width, height, blurDataURL });
  console.log(`✓ ${slug}  ${width}×${height}`);
}

const body = `// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
export type WorkImage = {
  slug: string;
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
};

export const workImages: Record<string, WorkImage> = ${JSON.stringify(
  Object.fromEntries(records.map((r) => [r.slug, r])),
  null,
  2,
)};
`;

await writeFile(DATA, body);
console.log(`\nWrote ${records.length} images → ${path.relative(root, DATA)}`);
